#!/usr/bin/env node
var geojsonDedupe = require('./'),
    stream = geojsonDedupe.dedupeStream,
    argv = require('minimist')(process.argv.slice(2));

// if (!argv._.length || argv.help) {
//   console.log('usage: geojson-dedupe < INPUT_FILE > OUTPUT_FILE');
//   return;
// }

process.stdin
    .pipe(stream(argv._))
    .pipe(process.stdout);